imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@IpcBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        enabled: true
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 86400
        cookie_samesite: 'lax'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    serializer:
        enabled: true
        enable_annotations: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        #prefix_image: "/BoilerBox"
        prefix_image: "" 
        # URL de dev :
        url_cloud: 'http://vps614872.ovh.net:8081/'
        # URL du cloud LTS
        #url_cloud: 'http://cloud.boiler-box-lts.fr/'
        # URL du cloud LCI
        url_cloud: 'http://cloud.boiler-box.fr/'
        # URL du cloud LCI PREPROD
        #url_cloud: 'http://preprodcloud.boiler-box.fr/'


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                #unix_socket: "%socket_unix%"
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: "%kernel.root_dir%/data/data.db3"
                # path:     "%database_path%"
            boilerbox_dev:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "boilerbox_dev"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                #unix_socket: "%socket_unix%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
            boilerbox_dev:
                connection: boilerbox_dev
                #mappings:
                #     FOSUserBundle: ~
                #    IpcProgBundle: ~
                #    IpcUserBundle: ~
                #    IpcConfigurationBundle: ~
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Lci\BoilerBoxBundle\Entity\User
    registration:
        form:
            type: 'Lci\BoilerBoxBundle\Form\Type\RegistrationFormType'
        confirmation:
            enabled: true
            from_email: 
                # Expediteur
                address: 'Assistance_IBC@lci-group.fr'
                # Nom de l'expediteur
                sender_name: 'Administrateur BoilerBox'
            template: '@FOSUser/Registration/email.txt.twig'
    resetting:
        email: 
            from_email:
                # Expediteur
                address: 'Assistance_IBC@lci-group.fr'
                # Nom de l'expediteur
                sender_name: 'Administrateur BoilerBox'
            template: '@FOSUser/Resetting/email.txt.twig'
    change_password:
        form: 
            type: 'Lci\BoilerBoxBundle\Form\Type\ChangePasswordFormType'
    from_email:
        address: "Assistance@lci-group.fr"
        sender_name: "Boiler-Box"
    service: 
        mailer: fos_user.mailer.twig_swift

sensio_framework_extra:
   router:
        annotations: false

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"

# Liste des routes disponibles en javascript : 
# Retour vers l'accueil : 									Appelée sur le bouton Annulation de certaines pages
# Enregistrement d'un nouveau site :						Appelée depuis la popup de la page d'accueil
# Appel de la page formulaire de Mise à jour d'un site : 	Appelée depuis la popup de la page d'accueil 
fos_js_routing:
     routes_to_expose: [ 'lci_boilerbox_index', 'lci_boilerbox_accesSite', 'lci_register_site', 'lci_register_site', 'lci_site_update', 'lci_gestion_admin', 'lci_accueil_register_user' ]
