<?php

namespace Ipc\ProgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonneetmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneetmpRepository extends EntityRepository
{
	public function countNb()
	{
		return $this->createQueryBuilder('d')
            ->select('COUNT(d)')
            ->getQuery()
            ->getSingleScalarResult();
	}



    public function hasData($offset) 
	{
        return $this->createQueryBuilder('d')
            ->select('d')
			->setMaxResults(1)
			->setFirstResult($offset)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
