<?php
namespace Ipc\ProgBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * DonneeLiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeLiveRepository extends EntityRepository
{
// Récupération de la liste des localisations du site courant
public function myFindByEntete($idLocalisation) {
	return $this 
		->createQueryBuilder('d')
		->leftJoin('d.typeFamille', 'tf')
		->addSelect('ABS(tf.disposition) AS HIDDEN disposition')
		->join('d.localisation', 'l')
		->where('l.id = :idlocalisation')
		->andWhere('d.placement = :placement')
		->addOrderBy('disposition', 'ASC')
		->addOrderBy('d.id', 'ASC')
		->setParameters(array('idlocalisation' => $idLocalisation, 'placement' => 'enTete'))
		->getQuery()
		->getResult();
}

public function myFindByNotEntete($idLocalisation)
{
	return $this
		->createQueryBuilder('d')
		->addSelect('ABS(d.famille) AS HIDDEN fam')
		->join('d.localisation', 'l')
		->where('l.id = :idlocalisation')
		->andWhere('d.placement != :placement')
		->addOrderBy('fam', 'ASC')
		->addOrderBy('d.id', 'ASC')
		->setParameters(array('idlocalisation' => $idLocalisation, 'placement' => 'enTete'))
		->getQuery()
		->getResult();
}
}
