<?php

namespace Ipc\ProgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends EntityRepository
{
    //	Récupération de la liste des localisations du site courant
    public function getLocalisationsCourantes()
    {
        return $this
          	->createQueryBuilder('l')
	  		->join('l.site','s')
          	->where('s.siteCourant = :courant')
          	->setParameter('courant', true)
        ;
    }


    //  *********************************************************************************************************************************************************************************************************************
    //                                                          F o n c t i o n s    U t i l i s é e s    par le module L I S T I N G
    //  *********************************************************************************************************************************************************************************************************************

    public function SqlGetLocalisation($dbh, $siteId)
    {
        $donnees = null;
        $requete = "SELECT l.id AS id, l.numero_localisation AS numero_localisation, l.adresse_ip AS adresse_ip, l.designation AS designation, l.last_horodatage AS last_horodatage
                    FROM t_localisation l
                    WHERE  l.site_id = '$siteId'";
        if (($reponse = $dbh->query($requete)) != false) {
            $donnees = $reponse->fetchAll();
            $reponse->closeCursor();
        }
        return($donnees);
    }


    //  *********************************************************************************************************************************************************************************************************************
    //                                                          F o n c t i o n s    U t i l i s é e s    par le service [ ServiceRequeteType.php ]
    //  *********************************************************************************************************************************************************************************************************************
    public function SqlGetAllLocalisation($dbh)
    {
        $donnees = null;
        $requete = "SELECT id, numero_localisation, designation FROM t_localisation";
        if (($reponse = $dbh->query($requete)) != false) {
            $donnees = $reponse->fetchAll();
            $reponse->closeCursor();
        }
        return($donnees);
    }

    //  *********************************************************************************************************************************************************************************************************************
    //                                                          F o n c t i o n s    U t i l i s é e s    par le service [ ServiceImportBin.php ]
    //  *********************************************************************************************************************************************************************************************************************

    // Mise à jour du dernier horodatage de la localisation si la valeur fournit est > à la valeur de la localisation
    public function SqlUpdateLastHorodatage($dbh, $entity_localisation, $nouvelle_date) {
        $retour = null;
        if ($nouvelle_date > $entity_localisation->getLastHorodatage()) {
            $requete = "UPDATE t_localisation SET last_horodatage = '".$nouvelle_date->format('YmdHis')."' WHERE id = '".$entity_localisation->getId()."';";
            $retour = $dbh->exec($requete);
        }
        return($retour);
    }

}
