<?php

namespace Ipc\ProgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleEnteteLiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleEnteteLiveRepository extends EntityRepository
{
    public function findAll()
    {
	return $this->findBy(array(),array('designation' => 'ASC'));
    }
}
