<?php

namespace Lci\BoilerBoxBundle\Entity;

/**
 * CommentairesSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
