<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementRepository extends EntityRepository
{
    public function myFindEquipementsTries($colonne_tri, $ordre_tri){
        $colonne = 'e.'.$colonne_tri;
        $qb = $this->createQueryBuilder('e');
        $qb->addOrderBy($colonne, $ordre_tri);
        return $qb->getQuery()->getResult();
    }

}
