<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichierSiteBARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierSiteBARepository extends EntityRepository
{
}
