<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function myFindFirst(){
        $qb = $this->createQueryBuilder('m')
            ->orderBy('m.numero','ASC')
			->setFirstResult(0)
			->setMaxResults(1);
        return $qb->getQuery()->getSingleResult();
    }

	public function myFindModulesTries($colonne_tri, $ordre_tri){
		$colonne = 'm.'.$colonne_tri;
		$qb = $this->createQueryBuilder('m');
		$qb->addOrderBy($colonne, $ordre_tri);
		if ($colonne_tri != 'numero') {
			$qb->addOrderBy('m.numero', 'ASC');
		}
		return $qb->getQuery()->getResult();
	}

	public function myCountProblemesBloquants($entity_module){
		$qb = $this->createQueryBuilder('m')
			->leftJoin('m.problemeTechnique', 'p')
			->select('COUNT(m)');
		$qb->where($qb->expr()->eq('m.id', $entity_module->getId()));
		$qb->andWhere($qb->expr()->andX($qb->expr()->eq('p.bloquant', '1'),
										$qb->expr()->eq('p.cloture', '0')));
		return $qb->getQuery()->getSingleScalarResult();
	}


}
