<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    public function getForUser($dbh,$userId)
    {
	$requete = 'SELECT site_id FROM user_site WHERE user_id = '.$userId;
    }

    public function findAll()
    {
        return $this->findBy(array(), array('affaire' => 'ASC'));
    }

	public function myFindWithCommentaires($id) {
        return $this->createQueryBuilder('s')
            ->leftJoin('s.commentaires','c')
            ->addSelect('c')
            ->orderBy('s.affaire')
            ->where('s.id = ?1')
            ->setParameters(array(1 => $id))
            ->getQuery()
            ->getOneOrNullResult();
    }

	public function myFindByUser($e_user, $champs_de_tri, $ordre_de_tri) {
		$qb = $this->createQueryBuilder('s');
		$qb->leftJoin('s.users', 'u')
            ->where($qb->expr()->eq('u.id', $e_user->getId()))
			->orderBy('s.'.$champs_de_tri, $ordre_de_tri);
		return $qb->getQuery()->getResult();
	}
}
