<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteBARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteBARepository extends EntityRepository
{
	public function findAll() {
		return $this->findBy(array(), array('intitule' => 'ASC'));	
	}
}
