<?php

namespace Lci\BoilerBoxBundle\Entity;

/**
 * SiteConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
