<?php

namespace Lci\BoilerBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function findBySite($site) {
        $query = $this->createQueryBuilder('u')
                      ->select('u')
                      ->leftJoin('u.site', 's')
                      ->addSelect('s');
 
        $query = $query->add('where', $query->expr()->in('s', ':s'))
                      ->setParameter('s', $site)
                      ->getQuery()
                      ->getResult();
          
        return $query;
    }

	// Retourne la liste des utilisateurs ayant le rôle défini
	public function myfindByRole($role) {
		$qb = $this->_em->createQueryBuilder()
			->select('u')
			->from($this->_entityName, 'u')
			->where('u.roles LIKE :role')
			->andWhere('u.enabled = 1')
			->setParameter('role', '%"'.$role.'"%');
		return $qb->getQuery()->getResult();
	
	}

	// Retourne les mails des utilisateurs ayant le rôle défini
    public function findEmailByRole($role) {
        $qb = $this->_em->createQueryBuilder()
            ->select('u.email')
            ->from($this->_entityName, 'u')
            ->where('u.roles LIKE :role')
            ->andWhere('u.enabled = 1')
            ->setParameter('role', '%"'.$role.'"%');
        return array_column($qb->getQuery()->getScalarResult(), 'email');

    }

}
