saisie_ticket:
    path: /saisie
    defaults: { _controller: LciBoilerBoxBundle:Ticket:saisie }
affiche_ticket:
    path: /affiche
    defaults: { _controller: LciBoilerBoxBundle:Ticket:afficherUnTicket }
envoi_mail_cloture:
    path: /envoi_mail_cloture
    defaults: { _controller: LciBoilerBoxBundle:AjaxTicket:sendEmailClotureTicketClient }

